name: Deploy Java Azure Function

on:
  push:
    branches:
      - main
    paths:
      - 'java-functionapp/**'
      - '.github/workflows/java-functionapp.yml'

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  JAVA_VERSION: '17'
  FUNCTION_APP_NAME: function-java

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F521763185294E34870C8C87EFE764F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_88283F2DA83B4EF089E591EA59BA58BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6E8BFA63F641409F93E516E148E49684 }}

      - name: Build Azure Function
        run: |
          mvn --batch-mode --update-snapshots -f java-functionapp/pom.xml clean package -DfunctionAppName="$FUNCTION_APP_NAME"

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: function-java
          package: java-functionapp/target/azure-functions/function-java
